[build]
  base = "client"
  publish = "client/build"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://edutech-api.netlify.app/api"
  REACT_APP_APP_NAME = "EduTech Platform"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://edutech-api-staging.netlify.app/api"
  REACT_APP_APP_NAME = "EduTech Platform (Preview)"

[context.branch-deploy.environment]
  REACT_APP_API_URL = "http://localhost:5000/api"
  REACT_APP_APP_NAME = "EduTech Platform (Dev)"
