[build]
  base = "."
  publish = "client/build"
  command = "cd client && npm install && npm run build"

[build.environment]
  NODE_VERSION = "16"
  NPM_VERSION = "9"
  CI = "false"
  NPM_FLAGS = "--legacy-peer-deps"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/proxy/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "/.netlify/functions/proxy/api"
  REACT_APP_APP_NAME = "EduTech Platform"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "/.netlify/functions/proxy/api"
  REACT_APP_APP_NAME = "EduTech Platform (Preview)"

[context.branch-deploy.environment]
  REACT_APP_API_URL = "http://localhost:5000/api"
  REACT_APP_APP_NAME = "EduTech Platform (Dev)"
